import type { Metadata } from 'next';
import MenuRight from '@/components/Menu/MenuRight/MenuRight';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full">
          <div className="flex-1">{children}</div>
          <div className="w-48">
            <MenuRight />
          </div>
        </div>
      </body>
    </html>
  );
}
