import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MenuRight from '@/components/Menu/MenuRight/MenuRight';
import { useRouter } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div>{children}</div>
          <div className="w-48">
            <MenuRight currentPage={router} />
          </div>
        </div>
      </body>
    </html>
  );
}
